### ISSUE TITLE
Crash with ALMA data

### ISSUE THREAD

**Issue by TimothyADavis** [pjcigan/multicolorfits#1]
Hi Phil,

Hope all is well with you! Trying out this nice code now, and get a crash when I try to add my ALMA data to some hubble images:

Exception occurred in traits notification handler for object: <multicolorfits.multicolorfits_viewer object at 0x11e9f9e00>, trait: plotbutton_combined, old value: <undefined>, new value: 0
Traceback (most recent call last):
  File "/Users/tdavis/opt/anaconda3/envs/astroenv/lib/python3.8/site-packages/traits/trait_notifiers.py", line 381, in __call__
    self.handler(*args)
  File "/Users/tdavis/opt/anaconda3/envs/astroenv/lib/python3.8/site-packages/multicolorfits.py", line 1771, in _plotbutton_combined_fired
    self.combined_RGB=combine_multicolor( [pan.image_colorRGB for pan in [self.panel1,self.panel2,self.panel3,self.panel4] if pan.in_use==True], gamma=self.gamma)
  File "/Users/tdavis/opt/anaconda3/envs/astroenv/lib/python3.8/site-packages/multicolorfits.py", line 1056, in combine_multicolor
    combined_RGB=LinearStretch()(np.nansum(im_list_colorized,axis=0))
  File "<__array_function__ internals>", line 5, in nansum
  File "/Users/tdavis/opt/anaconda3/envs/astroenv/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 649, in nansum
    a, mask = _replace_nan(a, 0)
  File "/Users/tdavis/opt/anaconda3/envs/astroenv/lib/python3.8/site-packages/numpy/lib/nanfunctions.py", line 102, in _replace_nan
    mask = np.not_equal(a, a, dtype=bool)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by pjcigan** [comment]
After discussing with the OP privately, the issue was that the loaded images were not on the same pixel grid.  A message has now been added to the main panel on startup to clarify that currently images must be projected to the same grid before loading into the GUI.  On-the fly reprojection to a specified image header is planned for implementation in an upcoming release, time permitting.
