### ISSUE TITLE
Installing fails in clean conda environment

### ISSUE THREAD

**Issue by lboogaard** [pjcigan/multicolorfits#4]
Hi, it appears that a clean `pip install multicolorfits` fails with a `pyproject.toml`-related error (?)

More info and tracelog below.

System:
- macos 12.6.5
- conda version 22.11.1

Setup:
```
conda create -n mcf python=3.8   # also tested 3.11
conda activate mcf
pip install multicolorfits
```

Tracelog
```
Collecting multicolorfits
  Using cached multicolorfits-2.1.0.tar.gz (17.4 MB)
  Preparing metadata (setup.py) ... done
Collecting numpy (from multicolorfits)
  Using cached numpy-1.24.3-cp38-cp38-macosx_11_0_arm64.whl (13.8 MB)
Collecting matplotlib (from multicolorfits)
  Using cached matplotlib-3.7.1-cp38-cp38-macosx_11_0_arm64.whl (7.3 MB)
Collecting astropy (from multicolorfits)
  Using cached astropy-5.2.2-cp38-cp38-macosx_11_0_arm64.whl (6.8 MB)
Collecting scipy (from multicolorfits)
  Using cached scipy-1.10.1-cp38-cp38-macosx_12_0_arm64.whl (28.8 MB)
Collecting pyface (from multicolorfits)
  Using cached pyface-8.0.0-py3-none-any.whl (1.3 MB)
Collecting traits (from multicolorfits)
  Downloading traits-6.4.1-cp38-cp38-macosx_10_9_universal2.whl (5.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 7.2 MB/s eta 0:00:00
Collecting traitsui (from multicolorfits)
  Using cached traitsui-8.0.0-py3-none-any.whl (1.5 MB)
Collecting scikit-image (from multicolorfits)
  Downloading scikit_image-0.21.0-cp38-cp38-macosx_12_0_arm64.whl (12.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.3/12.3 MB 47.5 MB/s eta 0:00:00
Collecting pyqt5 (from multicolorfits)
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      Traceback (most recent call last):
        File "/Users/boogaard/miniconda3/envs/mcf/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/Users/boogaard/miniconda3/envs/mcf/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/boogaard/miniconda3/envs/mcf/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 152, in prepare_metadata_for_build_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/1d/8csy3p_95rj89h2fl7xgq1wm5n1l7r/T/pip-build-env-jv3qe6ko/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 46, in build_wheel
          project = AbstractProject.bootstrap('wheel',
        File "/private/var/folders/1d/8csy3p_95rj89h2fl7xgq1wm5n1l7r/T/pip-build-env-jv3qe6ko/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 87, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/1d/8csy3p_95rj89h2fl7xgq1wm5n1l7r/T/pip-build-env-jv3qe6ko/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 586, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 68, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/1d/8csy3p_95rj89h2fl7xgq1wm5n1l7r/T/pip-build-env-jv3qe6ko/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/1d/8csy3p_95rj89h2fl7xgq1wm5n1l7r/T/pip-build-env-jv3qe6ko/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 237, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/1d/8csy3p_95rj89h2fl7xgq1wm5n1l7r/T/pip-build-env-jv3qe6ko/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 69, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Comment by pjcigan** [comment]
Hello,

Try installing now with the latest version -- 2.1.1.

There are a couple of issues that popped up with recent updates in dependent packages that caused this, but I've changed the default imports to use PyQt6 now, which should solve the issues for python 3.10 and up.  

I'm also aware of a related issue for Macs with M1/M2 processors that wouldn't work with pyqt5 or pyqt4, but this switch to PyQt6 _should_ address that as well...  

I'll mention here for posterity and web searches that one workaround solution for issues on M1/M2 Macs with legacy Qt versions is to create a virtual environment with x86 architecture.  For example:
`CONDA_SUBDIR=osx-64 conda create -n myenv_x86 python=3.9`
`conda activate myenv_x86`
`conda config --env --set subdir osx-64`
`pip install multicolorfits`
`export ETS_QT4_IMPORTS=1`
Not at all elegant as a permanent fix, but it got things going at least, and useful for testing.
